// seed_db.js - CARGA MASIVA TOTAL (1º a 6º GRADO - CICLO COMPLETO NEM)
const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const dbPath = path.resolve(__dirname, 'nem_primaria.db');
const db = new sqlite3.Database(dbPath);

console.log("🚀 INICIANDO CARGA MASIVA DE DATOS (CICLO 2025-2026)...");

// MAPEO DE METODOLOGÍAS
const METODOS = {
    'Lenguaje': 'COMUNITARIOS',
    'Saberes y Pensamiento Científico': 'STEAM',
    'Ética, Naturaleza y Sociedades': 'ABP',
    'De lo Humano y lo Comunitario': 'SERVICIO'
};

const DATA_REAL = [
    // ================= 1º GRADO =================
    {g:1, c:'Lenguaje', p:'Nombrario de Grupo', lt:'18–25', esc:'Aula', f:'Septiembre', pda:'Escribe su nombre y lo compara con los de sus compañeros, lo usa para autoría, útiles, asistencia, etc.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Reglamento del aula', lt:'132–137', esc:'Aula', f:'Septiembre', pda:'Participa en la revisión y construcción de acuerdos y reglas de convivencia.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Conozco, cuido y aprecio mi comunidad', lt:'142–157', esc:'Comunidad', f:'Septiembre', pda:'Reconoce y descubre características y cambios (gustos, necesidades, capacidades) que le hacen una persona única.'},
    {g:1, c:'Lenguaje', p:'Así festejan las familias', lt:'22–31', esc:'Comunidad', f:'Septiembre', pda:'Expresa lo que sabe de su familia mediante objetos y relatos.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'México y la diversidad de símbolos', lt:'124–131', esc:'Aula', f:'Septiembre', pda:'Identifica y valora manifestaciones culturales y símbolos que identifican a la comunidad, pueblo o ciudad.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Mi comunidad Escolar', lt:'100–109', esc:'Escolar', f:'Septiembre', pda:'Identifica y valora manifestaciones culturales y símbolos de su comunidad escolar.'},
    {g:1, c:'Lenguaje', p:'Frases y expresiones de cortesía', lt:'80–89', esc:'Escolar', f:'Septiembre', pda:'Lee y representa textos ficticios; crea personajes y situaciones para reflexionar sobre la cortesía.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Juntos fomentamos la Lectura', lt:'184–197', esc:'Comunidad', f:'Octubre', pda:'Identifica y valora la presencia de diferentes lenguas y ofrece apoyos a sus pares.'},
    {g:1, c:'Lenguaje', p:'Historias de mi comunidad escolar', lt:'90–99', esc:'Escolar', f:'Octubre', pda:'Lee textos ficticios, crea personajes y situaciones para dramatizar.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Mi cuerpo y sus movimientos', lt:'194–205', esc:'Aula', f:'Octubre', pda:'Compara y representa las partes externas del cuerpo, sus funciones y acciones de cuidado.'},
    {g:1, c:'Lenguaje', p:'Juntos resolvemos problemas', lt:'10–21', esc:'Comunidad', f:'Octubre', pda:'Identifica necesidades, elabora textos y solicita intervención de autoridades.'},
    {g:1, c:'Lenguaje', p:'Así festejan en mi comunidad', lt:'22–31', esc:'Comunidad', f:'Octubre', pda:'Expresa conocimientos sobre su familia mediante objetos, eventos y relatos.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Un día de Fiesta en mi comunidad', lt:'198–211', esc:'Comunidad', f:'Octubre', pda:'Indaga y ubica referentes locales, características socioculturales y geográficas.'},
    {g:1, c:'Lenguaje', p:'¡Disfrutemos de las Bibliotecas!', lt:'38–49', esc:'Escolar', f:'Octubre', pda:'Explora portadores de texto (libros, revistas, documentos digitales) en su entorno.'},
    {g:1, c:'Lenguaje', p:'Yo me cuido, tú me cuidas', lt:'68–79', esc:'Escolar', f:'Noviembre', pda:'Identifica funciones de carteles, propone elaboración colectiva para lograr propósitos.'},
    {g:1, c:'Lenguaje', p:'Los héroes sin capa de nuestra comunidad', lt:'88–95', esc:'Comunidad', f:'Noviembre', pda:'Lee textos ficticios y crea personajes para dramatizar historias.'},
    {g:1, c:'Lenguaje', p:'Modelamos una vida de paz', lt:'60–67', esc:'Escolar', f:'Noviembre', pda:'Lee textos ficticios y crea representaciones artísticas (poema, pintura, escultura).'},
    {g:1, c:'Lenguaje', p:'Lotería de nuestras fiestas', lt:'50–59', esc:'Escolar', f:'Noviembre', pda:'Expresa lo que sabe de su familia a través de objetos, comidas, fotografías y relatos.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'En la comunidad todos importan', lt:'128–133', esc:'Comunidad', f:'Noviembre', pda:'Indaga en fuentes orales, escritas y digitales para construir la historia personal y comunitaria.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Jugamos y convivimos en un entorno seguro', lt:'174–183', esc:'Comunidad', f:'Noviembre', pda:'Reconoce la importancia de hábitos de higiene, prevención de riesgos y situaciones de violencia.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Celebramos la navidad', lt:'SN', esc:'Escolar', f:'Diciembre', pda:'Reconoce y valora manifestaciones culturales a través de relatos, cantos y manualidades.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Diálogo para la justicia', lt:'94–99', esc:'Aula', f:'Diciembre', pda:'Reconoce actos de violencia e injusticia y es sensible a cómo afectan a las personas y colectivos.'},
    {g:1, c:'Lenguaje', p:'Hagámoslo entre todos y todas', lt:'44–53', esc:'Comunidad', f:'Diciembre', pda:'Registra y expone información sobre un tema de interés; comparte la información con la comunidad.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Los beneficios de las plantas', lt:'120–127', esc:'Comunidad', f:'Enero', pda:'Identifica y describe responsabilidades compartidas en la familia, escuela y comunidad.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Mi derecho a la alimentación', lt:'98–105', esc:'Comunidad', f:'Enero', pda:'Relaciona la satisfacción de necesidades básicas (alimentación, salud, vivienda) con el ejercicio de derechos.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Transformar conflictos en bien', lt:'126–132', esc:'Escolar', f:'Enero', pda:'Analiza situaciones de conflicto y usa el diálogo para evitar la violencia y promover acuerdos.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Los microorganismos existen', lt:'114–119', esc:'Comunidad', f:'Enero', pda:'Reconoce formas de nombrar y comprender actividades humanas y su cronología.'},
    {g:1, c:'Lenguaje', p:'Arriba la vida, abajo el peligro', lt:'68–77', esc:'Comunidad', f:'Enero', pda:'Identifica funciones de carteles y propone elaboración colectiva para concientizar sobre seguridad vial.'},
    {g:1, c:'Lenguaje', p:'Baúl de Soluciones', lt:'26–35', esc:'Aula', f:'Enero', pda:'Escribe y dibuja para recordar mensajes, tareas, acuerdos y resolver conflictos.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'¿Cómo mover los objetos?', lt:'256–265', esc:'Comunidad', f:'Febrero', pda:'Observa, experimenta y registra trayectorias, rapidez y movimiento de objetos.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Mi cuerpo dentro de una burbuja', lt:'100–107', esc:'Aula', f:'Febrero', pda:'Analiza importancia del respeto al cuerpo y diferencia contacto sano del inadecuado.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Situaciones de riesgo en la escuela', lt:'132–139', esc:'Escolar', f:'Febrero', pda:'Reconoce capacidad para tomar decisiones responsables y distingue cuándo pedir ayuda.'},
    {g:1, c:'Lenguaje', p:'Somos y sentimos lo que comemos', lt:'68', esc:'Aula', f:'Febrero', pda:'Escribe/dibuja para registrar acuerdos y promover hábitos saludables.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Transformar conflictos en bien', lt:'126–132', esc:'Escolar', f:'Febrero', pda:'Analiza conflictos, identifica participantes y usa el diálogo para resolverlos.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Una escuela llena de emociones', lt:'156–165', esc:'Escolar', f:'Marzo', pda:'Explica situaciones cotidianas, propone acuerdos, identifica logros y cambios que fortalecen autonomía.'},
    {g:1, c:'Lenguaje', p:'¡Creemos Textos en Colectivo!', lt:'46', esc:'Aula', f:'Marzo', pda:'Reconoce que movimientos, imágenes y sonidos son lenguajes; experimenta con formas y colores.'},
    {g:1, c:'Lenguaje', p:'Somos y sentimos lo que comemos', lt:'68', esc:'Aula', f:'Marzo', pda:'Escribe/dibuja para registrar mensajes, acuerdos y promover hábitos saludables.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Dialogamos para la justicia', lt:'94–99', esc:'Aula', f:'Marzo', pda:'Reconoce actos de violencia, injusticia o discriminación y reflexiona cómo afectan.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'¿Qué Tan Resistente es un Tubo?', lt:'216–225', esc:'Aula', f:'Marzo', pda:'Experimenta con empujar/jalar objetos para observar cambios en movimiento, reposo o rapidez.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Los sonidos en la naturaleza', lt:'238–252', esc:'Escolar', f:'Marzo', pda:'Indaga y describe sonidos, experimenta con objetos, clasifica por intensidad, tono y duración.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'El Rincón de los juegos', lt:'178–191', esc:'Aula', f:'Abril', pda:'Colabora en la definición de normas básicas de convivencia en juegos y situaciones cotidianas.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Cuentaestrellas', lt:'238–255', esc:'Comunidad', f:'Abril', pda:'Describe cambios y regularidades del entorno natural durante el día y la noche.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Cuidado con los Azúcares', lt:'206–215', esc:'Aula', f:'Abril', pda:'Indaga, registra y compara consumo de alimentos y bebidas; explica beneficios de una dieta saludable.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'Nos Comprometemos con Seres Vivos', lt:'110–117', esc:'Escolar', f:'Abril', pda:'Reconoce existencia de seres vivos y componentes naturales, analiza formas de interactuar con ellos.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Construyo Resbaladillas', lt:'252–265', esc:'Escolar', f:'Abril', pda:'Compara longitudes, sopesa objetos, estima masas y comprueba con balanza.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Mi Huerto de Plantas Medicinales', lt:'214–225', esc:'Comunidad', f:'Abril', pda:'Identifica actividades que impactan en la naturaleza, registra, clasifica y propone acciones.'},
    {g:1, c:'Lenguaje', p:'¡Bailamos palabras musicalizadas!', lt:'54–67', esc:'Comunidad', f:'Mayo', pda:'Escucha y lee poemas, adivinanzas, trabalenguas; produce rimas y reconoce elementos sonoros.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'¡Rico y saludable!', lt:'204–213', esc:'Escolar', f:'Mayo', pda:'Elabora registros de datos (pictogramas, tablas) para responder preguntas de su interés.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Lámpara de Sol', lt:'226–233', esc:'Aula', f:'Mayo', pda:'Describe sucesión del día y la noche, registra actividades cronológicas con base en fenómenos naturales.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'¿Cómo construir un puente?', lt:'228–237', esc:'Escolar', f:'Mayo', pda:'Observa y experimenta con materiales; clasifica por propiedades y diseña un objeto o juguete.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Medida de Mi Cintura', lt:'190–203', esc:'Escolar', f:'Mayo', pda:'Compara y representa partes externas del cuerpo, explica funcionamiento y propone acciones de cuidado.'},
    {g:1, c:'Saberes y Pensamiento Científico', p:'Figuras geométricas en la naturaleza', lt:'214–227', esc:'Escolar', f:'Mayo', pda:'Representa objetos y seres usando figuras geométricas, describe sus propiedades con lenguaje formal.'},
    {g:1, c:'Ética, Naturaleza y Sociedades', p:'La importancia del Bosque', lt:'116–123', esc:'Aula', f:'Junio', pda:'Describe actividades cotidianas y su relación con la naturaleza para reconocer acciones que benefician o dañan.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Hablemos de empatía', lt:'152–167', esc:'Aula', f:'Junio', pda:'Reconoce características y cambios (gustos, necesidades, capacidades) para valorar la diversidad.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'La Salud ¡Mi Gran Derecho!', lt:'168–177', esc:'Aula', f:'Junio', pda:'Reconoce hábitos de higiene, limpieza y alimentación saludable; intercambia experiencias de prevención.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'El Rincón de los juegos', lt:'178–191', esc:'Aula', f:'Junio', pda:'Colabora en la definición de normas básicas de convivencia en juegos y situaciones cotidianas.'},
    {g:1, c:'Lenguaje', p:'Hagamos Historietas', lt:'56–67', esc:'Aula', f:'Junio', pda:'Interpreta historias, identifica elementos narrativos y crea cómics o improvisaciones teatrales.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Museo de las emociones', lt:'158–173', esc:'Comunidad', f:'Julio', pda:'Explica situaciones cotidianas de la escuela y casa, propone acuerdos que mejoren convivencia.'},
    {g:1, c:'De lo Humano y lo Comunitario', p:'Jugamos y Nos Cuidamos', lt:'142–155', esc:'Escolar', f:'Julio', pda:'Participa en juegos para explorar alternativas que permitan mantener una vida activa y saludable.'},

    // ================= 2º GRADO =================
    {g:2, c:'Lenguaje', p:'Conozcamos mejor para hacer equipo', lt:'10-17', esc:'Aula', f:'Septiembre', pda:'Expresa ideas y emociones del pasado familiar y comunitario a través de fotografías y objetos.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Cuidamos nuestra escuela', lt:'142-149', esc:'Escolar', f:'Septiembre', pda:'Relaciona actividades humanas con efectos en la naturaleza; identifica cambios para preservación.'},
    {g:2, c:'Lenguaje', p:'Jardín del lenguaje', lt:'34-47', esc:'Aula', f:'Septiembre', pda:'Indaga sobre lengua materna y otras lenguas; comprende y aprecia diversidad lingüística.'},
    {g:2, c:'Lenguaje', p:'Lo que nos gusta y nos disgusta', lt:'48-59', esc:'Aula', f:'Septiembre', pda:'Describe de forma oral y escrita objetos, lugares y seres vivos de su entorno.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Una biblioteca de empatía', lt:'220-231', esc:'Escolar', f:'Septiembre', pda:'Explora sus posibilidades y las de otras personas para mostrar empatía.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Familias diversas', lt:'162-171', esc:'Aula', f:'Septiembre', pda:'Valora la diversidad de familias y promueve el respeto.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Cuídame, también soy tu casa', lt:'172-179', esc:'Aula', f:'Septiembre', pda:'Se reconoce como parte del lugar donde vive y en relación con otros seres vivos.'},
    {g:2, c:'Saberes y Pensamiento Científico', p:'Se puede estirar', lt:'126-137', esc:'Aula', f:'Octubre', pda:'Experimenta con materiales para identificar deformación por fuerza.'},
    {g:2, c:'Saberes y Pensamiento Científico', p:'Una mano a la alimentación', lt:'114-125', esc:'Aula', f:'Octubre', pda:'Reconoce y clasifica alimentos y bebidas; describe alimentos producidos localmente.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Decir sí es mi derecho', lt:'148-161', esc:'Aula', f:'Octubre', pda:'Identifica y expresa rechazo frente a conductas violentas o de acoso.'},
    {g:2, c:'Saberes y Pensamiento Científico', p:'El compactador Escolar', lt:'130-139', esc:'Escolar', f:'Octubre', pda:'Experimenta con objetos de diversos materiales para identificar deformación.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Pintemos un mundo sin violencia', lt:'146-155', esc:'Comunidad', f:'Octubre', pda:'Analiza y dialoga sobre estereotipos de género; promueve actividades igualitarias.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Los perros en situación de calle', lt:'174-183', esc:'Comunidad', f:'Octubre', pda:'Reconoce importancia de la responsabilidad compartida; propone acciones comunitarias.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Mi comunidad a través del tiempo', lt:'260-273', esc:'Comunidad', f:'Octubre', pda:'Escribe sobre sucesos de su historia personal y familiar apoyado en dibujos.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Teatro Guiñol por la convivencia', lt:'236-249', esc:'Aula', f:'Noviembre', pda:'Propone prácticas de autocuidado, de no violencia y convivencia pacífica.'},
    {g:2, c:'Saberes y Pensamiento Científico', p:'Luces y sombras', lt:'126-137', esc:'Comunidad', f:'Noviembre', pda:'Explora y registra fuentes de luz; experimenta con materiales para generar sombras.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Nos reconocemos como parte de una comunidad', lt:'218-231', esc:'Comunidad', f:'Noviembre', pda:'Reconoce conocimientos, prácticas culturales y formas de organización.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Cazadores de emociones', lt:'232-245', esc:'Comunidad', f:'Noviembre', pda:'Experimenta comunicación y expresión corporal para mejorar la interacción.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Los espacios de riesgo en mi comunidad', lt:'194-205', esc:'Comunidad', f:'Noviembre', pda:'Valora su capacidad para tomar decisiones, distingue límites y riesgos.'},
    {g:2, c:'Lenguaje', p:'Libro de historia de emociones', lt:'40-51', esc:'Escolar', f:'Noviembre', pda:'Reconoce recursos gráficos de cómics; representa una historia inventada en colectivo.'},
    {g:2, c:'Lenguaje', p:'Celebremos la navidad', lt:'SN', esc:'Escolar', f:'Diciembre', pda:'Investiga costumbres y tradiciones navideñas en su comunidad y otras regiones.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Cuidamos los seres vivos', lt:'160-167', esc:'Escolar', f:'Diciembre', pda:'Se reconoce como parte del lugar donde vive; dialoga sobre responsabilidades hacia la naturaleza.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Todos construimos la paz', lt:'246-259', esc:'Comunidad', f:'Diciembre', pda:'Propone prácticas de autocuidado, de no violencia y convivencia pacífica.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Acciones comunitarias sostenibles', lt:'156-165', esc:'Comunidad', f:'Enero', pda:'Identifica cambios en la naturaleza y su relación con actividades humanas.'},
    {g:2, c:'Saberes y Pensamiento Científico', p:'Lo que cambia y lo que pertenece', lt:'104-115', esc:'Comunidad', f:'Enero', pda:'Indaga fenómenos naturales que ocurren en meses/años; observa cambios en la Luna.'},
    {g:2, c:'Saberes y Pensamiento Científico', p:'Un muñeco cabeza de pasto', lt:'116-129', esc:'Escolar', f:'Enero', pda:'Describe y registra cronológicamente fenómenos naturales en tablas y calendarios.'},
    {g:2, c:'Lenguaje', p:'Reconozco un estado de mi país', lt:'72-83', esc:'Escolar', f:'Enero', pda:'Indaga y registra información sobre manifestaciones culturales de cada estado.'},
    {g:2, c:'Lenguaje', p:'Nos reinventamos', lt:'18-33', esc:'Aula', f:'Enero', pda:'Comenta e investiga hechos relevantes; elabora notas informativas escritas.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Ante el acoso escolar', lt:'150-159', esc:'Escolar', f:'Enero', pda:'Identifica y expresa rechazo frente a conductas violentas y de acoso.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Convivencia armónica en el aula', lt:'194-199', esc:'Aula', f:'Febrero', pda:'Participa en la revisión y construcción de acuerdos y normas.'},
    {g:2, c:'Lenguaje', p:'Más monstruos, menos bolsas', lt:'56-71', esc:'Comunidad', f:'Febrero', pda:'Identifica problemáticas sociales y ambientales de su comunidad.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Cuidemos nuestros recursos naturales', lt:'SN', esc:'Escolar', f:'Febrero', pda:'Reconoce la importancia de los recursos naturales; propone acciones de ahorro.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Revisando la bolsa del mandado', lt:'232-241', esc:'Escolar', f:'Febrero', pda:'Reflexiona sobre comportamientos de riesgo; compara alimentos naturales y procesados.'},
    {g:2, c:'Lenguaje', p:'El árbol de los campeones', lt:'74-87', esc:'Aula', f:'Febrero', pda:'Reconoce características y funciones de anuncios publicitarios; elabora avisos.'},
    {g:2, c:'Lenguaje', p:'La diversidad nos enriquece', lt:'72-89', esc:'Comunidad', f:'Marzo', pda:'Reconoce y valora símbolos nacionales; representa cambios en la vida cotidiana.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Yoga y emociones', lt:'204-219', esc:'Escolar', f:'Marzo', pda:'Combina patrones básicos de movimiento; fomenta bienestar físico y emocional.'},
    {g:2, c:'Lenguaje', p:'Mitos y leyendas sobre fenómenos', lt:'60-73', esc:'Aula', f:'Marzo', pda:'Construye personajes; investiga formas de vida; reconoce uso cultural de vestuario.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Mi compromiso con mi casa', lt:'168-175', esc:'Escolar', f:'Marzo', pda:'Reconoce que su vida depende de la naturaleza; analiza acciones que afectan especies.'},
    {g:2, c:'De lo Humano y lo Comunitario', p:'Feria de la Salud', lt:'208-217', esc:'Comunidad', f:'Abril', pda:'Reflexiona sobre comportamientos de riesgo; socializa alternativas de solución.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Cuidemos el agua, nuestros derechos', lt:'140-147', esc:'Aula', f:'Abril', pda:'Relaciona actividades humanas con la naturaleza; identifica acciones de cuidado del agua.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Juguemos futbol sin conflictos', lt:'194-201', esc:'Escolar', f:'Abril', pda:'Analiza responsabilidades de las autoridades; establece compromisos para colaborar.'},
    {g:2, c:'Lenguaje', p:'Si el oficio has de tener', lt:'34-43', esc:'Comunidad', f:'Abril', pda:'Formula y ajusta preguntas; recupera información escuchada en entrevistas.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Actividades artesanales', lt:'184-193', esc:'Escolar', f:'Mayo', pda:'Reconoce y valora símbolos nacionales; representa cambios en la vida cotidiana.'},
    {g:2, c:'Lenguaje', p:'Había una vez una obra de teatro', lt:'10-25', esc:'Escolar', f:'Mayo', pda:'Explora elementos de los cuentos; representa historias por medio de títeres.'},
    {g:2, c:'Lenguaje', p:'Las fiestas de nuestra comunidad', lt:'44-55', esc:'Comunidad', f:'Mayo', pda:'Formula y ajusta preguntas para recuperar información de celebraciones.'},
    {g:2, c:'Saberes y Pensamiento Científico', p:'Nos preparamos ante desastres', lt:'300-315', esc:'Escolar', f:'Mayo', pda:'Identifica riesgos en la escuela; propone acciones preventivas y protocolos.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Productos hechos a mano', lt:'166-173', esc:'Comunidad', f:'Mayo', pda:'Reconoce y valora la importancia de las prácticas culturales y artesanales.'},
    {g:2, c:'Lenguaje', p:'El muro de los deseos', lt:'60-71', esc:'Escolar', f:'Junio', pda:'Reconoce características y funciones de anuncios publicitarios; elabora avisos.'},
    {g:2, c:'Lenguaje', p:'Instalando sensaciones', lt:'52-59', esc:'Escolar', f:'Junio', pda:'Representa situaciones cotidianas mediante sonidos, movimientos e imágenes.'},
    {g:2, c:'Ética, Naturaleza y Sociedades', p:'Los saberes de mi comunidad', lt:'186-193', esc:'Aula', f:'Junio', pda:'Indaga cambios en la vida cotidiana; los representa con dibujos y líneas del tiempo.'},
    {g:2, c:'Lenguaje', p:'Nos divertimos con juegos tradicionales', lt:'10-21', esc:'Comunidad', f:'Junio', pda:'Realiza actividades a partir de la lectura de instructivos; escribe instrucciones.'},
    {g:2, c:'Lenguaje', p:'Libro de álbum de historias y emociones', lt:'40-51', esc:'Escolar', f:'Julio', pda:'Lee historietas sencillas, reconoce recursos gráficos y elabora cómics colectivos.'},

    // ================= 3º GRADO =================
    {g:3, c:'De lo Humano y lo Comunitario', p:'¿A dónde pertenezco?', lt:'262-283', esc:'Comunidad', f:'Septiembre', pda:'Identifica eventos importantes de la historia de la comunidad (fundación, logros).'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Acordamos reglas para convivir', lt:'278-287', esc:'Escolar', f:'Septiembre', pda:'Participa en la organización del aula y en la generación de normas.'},
    {g:3, c:'Lenguaje', p:'Libros cartoneros', lt:'86-99', esc:'Aula', f:'Septiembre', pda:'Identifica y reflexiona sobre la función de textos instructivos.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Uno, dos y tres por mi familia', lt:'234-245', esc:'Aula', f:'Septiembre', pda:'Identifica formas de convivencia y socialización en la familia.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Prevenimos los riesgos', lt:'242-251', esc:'Escolar', f:'Septiembre', pda:'Indaga desastres ocurridos en la localidad; identifica zonas de seguridad.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'La asamblea escolar', lt:'208-217', esc:'Comunidad', f:'Septiembre', pda:'Analiza necesidades básicas y derechos; propone acciones comunitarias.'},
    {g:3, c:'Lenguaje', p:'Quiero conocer la historia', lt:'58-71', esc:'Comunidad', f:'Septiembre', pda:'Redacta descripciones detalladas; organiza información cronológica.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'¿Cómo convivimos en la escuela?', lt:'266-277', esc:'Escolar', f:'Octubre', pda:'Participa en situaciones para acordar reglas; reflexiona cumplimiento.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Decidimos y convivimos', lt:'280-293', esc:'Aula', f:'Octubre', pda:'Toma decisiones estratégicas en situaciones de juego y cotidianas.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Recorrido por nuestro espacio vital', lt:'180-193', esc:'Comunidad', f:'Octubre', pda:'Representa cartográficamente el territorio; indaga interacciones comunidad-ecosistema.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Hablemos de higiene', lt:'312-325', esc:'Aula', f:'Octubre', pda:'Reflexiona sobre prácticas de higiene de la vida cotidiana.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Libro cartonero identidad', lt:'264-279', esc:'Aula', f:'Octubre', pda:'Reconoce características que lo hacen diferente y único.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Reporteros de la justica', lt:'232-245', esc:'Comunidad', f:'Octubre', pda:'Comprende democracia como práctica en la vida cotidiana; participa en normas.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Ganar, ganar', lt:'102-113', esc:'Comunidad', f:'Octubre', pda:'Explica importancia de alimentación higiénica y variada.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'¿Cómo convivimos en la escuela?', lt:'266-277', esc:'Escolar', f:'Noviembre', pda:'Participa en situaciones para acordar reglas; reflexiona cumplimiento.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Decidimos y convivimos', lt:'280-293', esc:'Aula', f:'Noviembre', pda:'Toma decisiones estratégicas en situaciones de juego.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Recorrido por nuestro espacio vital', lt:'180-193', esc:'Comunidad', f:'Noviembre', pda:'Representa cartográficamente el territorio; indaga interacciones.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Hablemos de higiene', lt:'312-325', esc:'Aula', f:'Noviembre', pda:'Reflexiona sobre prácticas de higiene de la vida cotidiana.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Libro cartonero identidad', lt:'264-279', esc:'Aula', f:'Noviembre', pda:'Reconoce características que lo hacen diferente y único.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Reporteros de la justica', lt:'232-245', esc:'Comunidad', f:'Noviembre', pda:'Comprende democracia como práctica cotidiana.'},
    {g:3, c:'Lenguaje', p:'Nosotros y las cartas', lt:'72-85', esc:'Comunidad', f:'Diciembre', pda:'Lee y comenta cartas reales; identifica funciones.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Celebremos la navidad', lt:'340-355', esc:'Escolar', f:'Diciembre', pda:'Identifica costumbres y tradiciones navideñas.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'La fuerza musical en movimiento', lt:'150-161', esc:'Aula', f:'Diciembre', pda:'Describe movimientos; analiza efectos de las fuerzas.'},
    {g:3, c:'Lenguaje', p:'El placer de aprender instructivos', lt:'26-39', esc:'Escolar', f:'Enero', pda:'Identifica y reflexiona sobre textos instructivos.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Mantener la temperatura', lt:'162-173', esc:'Escolar', f:'Enero', pda:'Experimenta con cambios en rapidez y dirección; analiza transferencia de calor.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'¿Qué hace que me mueva?', lt:'102-115', esc:'Aula', f:'Enero', pda:'Identifica y describe sistemas óseo y muscular.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Agricultores de la paz', lt:'212-219', esc:'Aula', f:'Enero', pda:'Reconoce que la paz se construye dialogando.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Clasificamos, reducimos y reutilizamos', lt:'246-263', esc:'Aula', f:'Enero', pda:'Participa en la organización del aula; reflexiona sobre problemas ambientales.'},
    {g:3, c:'Lenguaje', p:'Las rimas como el pan', lt:'88-103', esc:'Escolar', f:'Enero', pda:'Reconoce rima y aliteración; crea canciones y juegos de palabras.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Trato igualitario', lt:'220-229', esc:'Escolar', f:'Enero', pda:'Analiza e identifica situaciones de discriminación.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Los símbolos me dan identidad', lt:'220-231', esc:'Aula', f:'Febrero', pda:'Indaga símbolos de identidad en comunidad.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Un tianguis en mi escuela', lt:'338-353', esc:'Escolar', f:'Febrero', pda:'Distingue alimentos saludables; promueve alimentación equilibrada.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Siento, pienso y decido', lt:'294-311', esc:'Aula', f:'Febrero', pda:'Reconoce riesgos sociales; analiza medidas de autocuidado.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'La vida en movimiento', lt:'114-131', esc:'Comunidad', f:'Febrero', pda:'Describe locomoción de animales; clasifica vertebrados e invertebrados.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Cuando él no está', lt:'144-161', esc:'Comunidad', f:'Febrero', pda:'Explica importancia del aire, agua, suelo y sol.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Construyamos un carro', lt:'144-161', esc:'Escolar', f:'Febrero', pda:'Representa movimientos; describe efecto de las fuerzas.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'El jardín del Sol', lt:'174-193', esc:'Escolar', f:'Marzo', pda:'Realiza observaciones de astros; analiza fenómenos naturales.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Prevenimos riesgo en la escuela', lt:'242-251', esc:'Escolar', f:'Marzo', pda:'Indaga desastres ocurridos; localiza zonas de seguridad.'},
    {g:3, c:'Lenguaje', p:'Seamos periodistas', lt:'86-99', esc:'Comunidad', f:'Marzo', pda:'Identifica elementos de la noticia; distingue información y opinión.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Somos diferentes pero jugamos', lt:'116-131', esc:'Aula', f:'Marzo', pda:'Reconoce diferencias sexuales; identifica acciones de autocuidado.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Contra estereotipos de género', lt:'200-211', esc:'Aula', f:'Marzo', pda:'Analiza casos de discriminación; promueve trato igualitario.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Expo actívate', lt:'320-337', esc:'Escolar', f:'Abril', pda:'Establece acuerdos en juegos; valora convivencia.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Croquis de mi comunidad', lt:'176-185', esc:'Aula', f:'Abril', pda:'Elabora representaciones cartográficas; indaga ecosistemas.'},
    {g:3, c:'Lenguaje', p:'Rutas de mi localidad', lt:'72-87', esc:'Escolar', f:'Abril', pda:'Reconoce convenciones gráficas; describe trayectos.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Ladrillos con residuos', lt:'162-177', esc:'Comunidad', f:'Abril', pda:'Indaga impactos de actividades humanas; analiza causa-efecto.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Preparar alimentos sanos', lt:'132-149', esc:'Aula', f:'Abril', pda:'Explica importancia de alimentación variada.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'La fuerza musical en movimiento', lt:'150-161', esc:'Aula', f:'Abril', pda:'Describe movimientos; analiza efecto de las fuerzas.'},
    {g:3, c:'Lenguaje', p:'Una historia extraordinaria', lt:'20-31', esc:'Comunidad', f:'Mayo', pda:'Reconoce función del resumen; selecciona información relevante.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Participamos por el bienestar', lt:'246-259', esc:'Comunidad', f:'Mayo', pda:'Investiga vida cotidiana de pueblos originarios.'},
    {g:3, c:'Saberes y Pensamiento Científico', p:'Las formas de la naturaleza', lt:'132-143', esc:'Comunidad', f:'Mayo', pda:'Construye y clasifica figuras geométricas.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Cómo cuidamos los ecosistemas', lt:'196-209', esc:'Escolar', f:'Mayo', pda:'Representa cartográficamente el territorio; indaga interacciones.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Haz de tu escuela zona segura', lt:'230-241', esc:'Escolar', f:'Mayo', pda:'Indaga desastres; elabora croquis y mapas de prevención.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Jornada prevención violencia', lt:'338-353', esc:'Comunidad', f:'Mayo', pda:'Analiza situaciones de violencia; propone medidas de autocuidado.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Recorrido por nuestro espacio', lt:'180-193', esc:'Comunidad', f:'Junio', pda:'Representa cartográficamente el territorio; indaga interacciones.'},
    {g:3, c:'Lenguaje', p:'MI amigo el ajolote', lt:'48-57', esc:'Comunidad', f:'Junio', pda:'Comprende textos expositivos; identifica semejanzas y diferencias.'},
    {g:3, c:'Ética, Naturaleza y Sociedades', p:'Aportes culturales', lt:'194-207', esc:'Comunidad', f:'Junio', pda:'Conoce y analiza cosmovisiones de pueblos originarios.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'¿A dónde pertenezco?', lt:'262-283', esc:'Comunidad', f:'Junio', pda:'Identifica eventos importantes de la historia de la comunidad.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Juegos Olímpicos Comunitarios', lt:'308-319', esc:'Comunidad', f:'Junio', pda:'Socializa actividades físicas; valora bienestar.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Decidimos y convivimos', lt:'280-293', esc:'Aula', f:'Junio', pda:'Toma decisiones estratégicas en juegos.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'¿Qué te dice mi cuerpo?', lt:'302-319', esc:'Escolar', f:'Julio', pda:'Elabora códigos de comunicación corporal.'},
    {g:3, c:'De lo Humano y lo Comunitario', p:'Galería de mi comunidad', lt:'296-307', esc:'Comunidad', f:'Julio', pda:'Identifica eventos importantes de la comunidad.'},

    // ================= 4º GRADO =================
    {g:4, c:'Lenguaje', p:'Aprendo a escuchar para dialogar', lt:'10-21', esc:'Aula', f:'Septiembre', pda:'Indica de manera respetuosa cuando no comprende; practica escucha activa.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'Detectives del conflicto', lt:'246-255', esc:'Aula', f:'Septiembre', pda:'Comprende que la paz es construcción colectiva; analiza conflictos.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'Iguales pero diferentes', lt:'220-229', esc:'Escolar', f:'Septiembre', pda:'Conoce y analiza críticamente situaciones de discriminación.'},
    {g:4, c:'Lenguaje', p:'México lindo ¡qué ritmo!', lt:'96-109', esc:'Aula', f:'Septiembre', pda:'Reconoce contexto de creación de poemas y canciones.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'¿Cómo es tu familia?', lt:'270-279', esc:'Aula', f:'Septiembre', pda:'Reflexiona sobre el valor de la familia y su aporte al desarrollo.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Conocer el lugar donde vivimos', lt:'268-277', esc:'Comunidad', f:'Septiembre', pda:'Aprecia los aportes de las personas a la comunidad.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'Nos preparamos para estar a salvo', lt:'230-239', esc:'Escolar', f:'Septiembre', pda:'Indaga fuentes sobre desastres; elabora mapas y protocolos.'},
    {g:4, c:'Lenguaje', p:'Serás la arquitecta de tu escuela', lt:'124-139', esc:'Escolar', f:'Octubre', pda:'Observa e interpreta mapas; identifica convenciones gráficas.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'La higiene tu mejor aliada', lt:'336-353', esc:'Escolar', f:'Octubre', pda:'Comparte experiencias para mejorar higiene en escuela y comunidad.'},
    {g:4, c:'Lenguaje', p:'Así eran las familias', lt:'10-23', esc:'Comunidad', f:'Octubre', pda:'Reconoce y usa estilos y recursos narrativos.'},
    {g:4, c:'Lenguaje', p:'Nuestra revista escolar', lt:'10-25', esc:'Escolar', f:'Octubre', pda:'Identifica efectos en texto expositivo; planea y redacta.'},
    {g:4, c:'Lenguaje', p:'Actuemos por alimentación saludable', lt:'10-25', esc:'Escolar', f:'Octubre', pda:'Identifica efectos en texto expositivo; propone soluciones.'},
    {g:4, c:'Lenguaje', p:'Con Pan…¡Festejamos!', lt:'24-43', esc:'Comunidad', f:'Noviembre', pda:'Planea, escribe y revisa descripciones; usa adjetivos.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Una historia de mi comunidad', lt:'318-327', esc:'Comunidad', f:'Noviembre', pda:'Reconstruye historia de familia, escuela y comunidad.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'De la cartografía a la riqueza', lt:'206-217', esc:'Aula', f:'Noviembre', pda:'Localiza y reconoce características del territorio nacional.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Moviendo mi cuerpo', lt:'300-307', esc:'Escolar', f:'Noviembre', pda:'Reconoce sus capacidades motrices, representa con el cuerpo.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'Álbum de historias y conflictos', lt:'256-267', esc:'Aula', f:'Noviembre', pda:'Reconoce e indaga sobre símbolos nacionales.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Reciclamos la vida', lt:'162-175', esc:'Comunidad', f:'Noviembre', pda:'Indaga y describe problemas de contaminación.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'La aventura de la comida', lt:'124-139', esc:'Aula', f:'Noviembre', pda:'Identifica y describe estructura del sistema digestivo.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'El juego es espacio para todos', lt:'294-309', esc:'Aula', f:'Diciembre', pda:'Experimenta situaciones cooperativas en juegos.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Celebremos la navidad', lt:'SN', esc:'Escolar', f:'Diciembre', pda:'Reconoce costumbres y tradiciones navideñas.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'La higiene tú mejor aliada', lt:'336-353', esc:'Escolar', f:'Diciembre', pda:'Comparte experiencias para mejorar higiene.'},
    {g:4, c:'Lenguaje', p:'Niñas y niños somos noticia', lt:'22-33', esc:'Aula', f:'Enero', pda:'Conoce noticias en distintos medios, compara.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Mi cuerpo está cambiando', lt:'140-153', esc:'Aula', f:'Enero', pda:'Indaga y representa cambios sexuales primarios y secundarios.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Desalinizando el agua', lt:'168-183', esc:'Escolar', f:'Enero', pda:'Diseña y construye prototipo para separar sal del agua.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Yo en el mundo de colores', lt:'310-325', esc:'Aula', f:'Enero', pda:'Identifica expresiones emocionales, reflexiona cualidades.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Rompecabezas Plato Bien Comer', lt:'154-173', esc:'Aula', f:'Enero', pda:'Indaga nutrimentos, analiza influencia de medios.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Comprar con responsabilidad', lt:'120-131', esc:'Comunidad', f:'Enero', pda:'Resuelve problemas con operaciones, analiza gasto familiar.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Optimizando las fuerzas', lt:'174-193', esc:'Aula', f:'Febrero', pda:'Experimenta con fricción y calor.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Comer bien, vivir bien', lt:'328-341', esc:'Comunidad', f:'Febrero', pda:'Analiza características de alimentación saludable.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'Pasado y presente de la igualdad', lt:'234-245', esc:'Aula', f:'Febrero', pda:'Analiza desigualdades de género.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Cuando cambio ¿Por qué?', lt:'142-153', esc:'Escolar', f:'Febrero', pda:'Investiga cambios biológicos, analiza estados de agregación.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'De la cartografía a la riqueza', lt:'206-217', esc:'Aula', f:'Febrero', pda:'Localiza y reconoce características del territorio nacional.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'La Tierra, Luz del Sol y Luna', lt:'184-195', esc:'Escolar', f:'Marzo', pda:'Indaga eclipses y fenómenos astronómicos.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Saber escuchar para acuerdos', lt:'264-271', esc:'Escolar', f:'Marzo', pda:'Comparte ideas, escucha distintos puntos de vista.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'El papel de las mujeres', lt:'196-205', esc:'Aula', f:'Marzo', pda:'Representa relevancia de mujeres en familia y comunidad.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Luces, cámara, equidad', lt:'278-299', esc:'Comunidad', f:'Marzo', pda:'Reflexiona sobre estilos de relación, diseña videos.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Escuela Divertida, Saludable', lt:'308-323', esc:'Escolar', f:'Marzo', pda:'Organiza juegos y actividades físicas.'},
    {g:4, c:'Lenguaje', p:'Profesiones no tienen género', lt:'26-43', esc:'Escolar', f:'Marzo', pda:'Identifica y produce textos discontinuos.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Festival de talentos', lt:'272-287', esc:'Escolar', f:'Abril', pda:'Comparte cambios en capacidades, participa en festival.'},
    {g:4, c:'Lenguaje', p:'Un viaje a través del tiempo', lt:'80-95', esc:'Aula', f:'Abril', pda:'Analiza cartas reales y literarias.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Todos jugamos, todos ganamos', lt:'288-299', esc:'Escolar', f:'Abril', pda:'Diseña estrategias para resolver problemas en juegos.'},
    {g:4, c:'Lenguaje', p:'No pierdas el tino', lt:'44-55', esc:'Escolar', f:'Abril', pda:'Analiza características de textos instructivos.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Me informo para prevenir', lt:'342-353', esc:'Comunidad', f:'Abril', pda:'Analiza riesgos sociales, propone medidas autocuidado.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'Nos preparamos para estar a salvo', lt:'230-239', esc:'Escolar', f:'Mayo', pda:'Indaga sobre desastres, elabora mapas y protocolos.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'El Comité Escolar', lt:'324-335', esc:'Escolar', f:'Mayo', pda:'Participa en toma de decisiones, propone mejoras.'},
    {g:4, c:'Lenguaje', p:'Cuéntame tu historia', lt:'104-117', esc:'Comunidad', f:'Mayo', pda:'Analiza manifestaciones culturales, crea personajes.'},
    {g:4, c:'Lenguaje', p:'Hagamos talleres de teatro', lt:'92-105', esc:'Escolar', f:'Mayo', pda:'Explora movimiento, gesto y sonido.'},
    {g:4, c:'Lenguaje', p:'La poesía en la vida cotidiana', lt:'76-91', esc:'Escolar', f:'Mayo', pda:'Reconoce contexto de creación, interpreta significados.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'El trueque en la comunidad', lt:'186-201', esc:'Comunidad', f:'Junio', pda:'Reconoce relación comunidad-naturaleza.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Exposición de prototipos', lt:'280-293', esc:'Escolar', f:'Junio', pda:'Participa en decisiones, propone mejoras.'},
    {g:4, c:'Ética, Naturaleza y Sociedades', p:'Periodistas de la desigualdad', lt:'252-261', esc:'Escolar', f:'Junio', pda:'Investiga fuentes conquista, identifica desigualdades.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Optimizando las fuerzas', lt:'174-193', esc:'Aula', f:'Junio', pda:'Comprende fricción y transferencia de calor.'},
    {g:4, c:'Saberes y Pensamiento Científico', p:'Todas y todos a escena', lt:'154-167', esc:'Escolar', f:'Junio', pda:'Identifica desplazamientos, diseña croquis.'},
    {g:4, c:'Lenguaje', p:'Anécdotas animadas', lt:'88-103', esc:'Comunidad', f:'Julio', pda:'Lee y escucha cuentos, reflexiona tiempos verbales.'},
    {g:4, c:'De lo Humano y lo Comunitario', p:'Tomamos decisiones asertivas', lt:'326-339', esc:'Aula', f:'Julio', pda:'Desarrolla habilidades para reconocer reacciones emocionales.'},

    // ================= 5º GRADO =================
    {g:5, c:'Lenguaje', p:'Acordamos normas y reglas', lt:'64-79', esc:'Aula', f:'Septiembre', pda:'Analiza reglamentos escolares, comprende función y participa en elaboración.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Construyamos ideas para la paz', lt:'246-261', esc:'Escolar', f:'Septiembre', pda:'Reflexiona sobre conflictos en escuela y familia, valora alternativas.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Dialogamos para vivir en paz', lt:'198-209', esc:'Escolar', f:'Septiembre', pda:'Indaga conflictos vecinales, analiza causas y resolución.'},
    {g:5, c:'Lenguaje', p:'Un mensaje para el futuro', lt:'24-36', esc:'Comunidad', f:'Septiembre', pda:'Lee y analiza cartas, reflexiona sobre su función.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'La injusticia social Independencia', lt:'218-236', esc:'Aula', f:'Septiembre', pda:'Indaga causas del movimiento de Independencia, analiza ideales.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Me reconozco a través de mi familia', lt:'266-277', esc:'Aula', f:'Septiembre', pda:'Participa en formas de convivencia familiar, reflexiona valores.'},
    {g:5, c:'Lenguaje', p:'Expres-arte con el cuerpo', lt:'90-103', esc:'Escolar', f:'Septiembre', pda:'Combina movimientos, gestos, sonidos; desarrolla narrativas.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'Un menú saludable', lt:'152-161', esc:'Aula', f:'Octubre', pda:'Explica dieta correcta, analiza riesgos, diseña menús.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'¿Agua virtual?', lt:'164-179', esc:'Comunidad', f:'Octubre', pda:'Indaga consumo de agua, analiza problemas, calcula agua virtual.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Dialoguemos para vivir en paz', lt:'198-209', esc:'Escolar', f:'Octubre', pda:'Indaga conflictos, analiza resolución, aplica mediación.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'¿Qué le sucedió a mi almuerzo?', lt:'130-155', esc:'Escolar', f:'Octubre', pda:'Describe cambios permanentes en alimentos.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Yo me cuido, cuidando comunidad', lt:'198-215', esc:'Comunidad', f:'Octubre', pda:'Comprende desastres no naturales, identifica agentes.'},
    {g:5, c:'Lenguaje', p:'Sonidos e imágenes de nuestro entorno', lt:'76-89', esc:'Escolar', f:'Octubre', pda:'Explora sonidos e imágenes, identifica contaminación.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Reporteros de la ética ambiental', lt:'182-197', esc:'Escolar', f:'Octubre', pda:'Dialoga sobre valores para conservar biodiversidad.'},
    {g:5, c:'Lenguaje', p:'Las historias que nos unen', lt:'50-64', esc:'Aula', f:'Noviembre', pda:'Reconoce características de reseñas, redacta opiniones.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'No al acoso escolar', lt:'208-217', esc:'Aula', f:'Noviembre', pda:'Analiza causas violencia de género, propone acciones.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Mexicanos defensa soberanía', lt:'236-245', esc:'Aula', f:'Noviembre', pda:'Indaga fuentes sobre vida cotidiana siglo XIX.'},
    {g:5, c:'Lenguaje', p:'Vamos al rescate', lt:'92-105', esc:'Comunidad', f:'Noviembre', pda:'Lee, investiga y comparte mitos y leyendas.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'Los seres vivos, muy vivos', lt:'108-123', esc:'Comunidad', f:'Noviembre', pda:'Explica reproducción en plantas, clasifica animales.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'¿Qué le sucedió a mi almuerzo?', lt:'130-155', esc:'Escolar', f:'Noviembre', pda:'Describe cocción y descomposición.'},
    {g:5, c:'Lenguaje', p:'Nuestra primera revista colectiva', lt:'46-57', esc:'Comunidad', f:'Noviembre', pda:'Investiga en distintos medios, produce revista.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Tianguis lúdico', lt:'316-325', esc:'Aula', f:'Diciembre', pda:'Planifica estrategias en juegos de mesa.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Celebremos la navidad', lt:'SN', esc:'Escolar', f:'Diciembre', pda:'Reconoce costumbres navideñas.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Coordinando ando', lt:'292-305', esc:'Escolar', f:'Diciembre', pda:'Reconoce límites y posibilidades en juegos.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'A mover el esqueleto', lt:'306-315', esc:'Aula', f:'Diciembre', pda:'Integra capacidades en situaciones lúdicas.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Migrar es un derecho humano', lt:'246-263', esc:'Aula', f:'Enero', pda:'Reconoce procesos de migración, analiza testimonios.'},
    {g:5, c:'Lenguaje', p:'Formular, formulario', lt:'58-67', esc:'Comunidad', f:'Enero', pda:'Explora formularios, reflexiona función.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Pensamos y protegemos biodiversidad', lt:'178-197', esc:'Aula', f:'Enero', pda:'Comprende funciones biodiversidad, indaga causas pérdida.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Servicios públicos', lt:'228-243', esc:'Comunidad', f:'Enero', pda:'Indaga necesidades comunidad, identifica servicios.'},
    {g:5, c:'Lenguaje', p:'Fragmentos de nuestra vida', lt:'22-37', esc:'Escolar', f:'Enero', pda:'Reconoce características textos discontinuos.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Protegemos datos personales', lt:'244-253', esc:'Comunidad', f:'Enero', pda:'Reconoce importancia proteger datos personales.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'El espacio entre tú y yo', lt:'118-129', esc:'Escolar', f:'Febrero', pda:'Experimenta con materiales, construye objetos.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'Una bomba en mi cuerpo', lt:'120-135', esc:'Aula', f:'Febrero', pda:'Describe y representa modelos órganos.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Antología saludable', lt:'306-319', esc:'Comunidad', f:'Febrero', pda:'Construye alternativas saludables alimentación.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'Jardín polinizadores', lt:'138-151', esc:'Comunidad', f:'Febrero', pda:'Indaga ecosistemas locales, diseña jardín.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Todos somos lo mismo', lt:'262-277', esc:'Escolar', f:'Febrero', pda:'Reflexiona sobre diversidad identidades.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Culturas contexto Americano', lt:'234-245', esc:'Escolar', f:'Febrero', pda:'Investiga vida cotidiana pueblos americanos.'},
    {g:5, c:'Lenguaje', p:'Perspectiva de género música', lt:'50-63', esc:'Escolar', f:'Marzo', pda:'Plantea propuestas creativas, modifica letras.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'Mi vuelo es la flor de vida', lt:'152-163', esc:'Comunidad', f:'Marzo', pda:'Analiza causas pérdida biodiversidad.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Estaciones activas', lt:'294-305', esc:'Comunidad', f:'Marzo', pda:'Propone alternativas actividades físicas.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'Astrónomos en acción', lt:'168-181', esc:'Escolar', f:'Marzo', pda:'Indaga características planetas.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Futuro sin discriminación', lt:'222-233', esc:'Escolar', f:'Marzo', pda:'Analiza casos racismo y discriminación.'},
    {g:5, c:'Lenguaje', p:'Sabores y saberes del maíz', lt:'80-91', esc:'Comunidad', f:'Abril', pda:'Analiza trípticos, elabora tríptico ilustrado.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Tianguis lúdico', lt:'316-325', esc:'Aula', f:'Abril', pda:'Planifica estrategias de juego.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'El cuerpo parlachín', lt:'306-319', esc:'Escolar', f:'Abril', pda:'Promueve ambientes de participación.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Foro de salud e higiene', lt:'320-331', esc:'Comunidad', f:'Abril', pda:'Construye alternativas saludables.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Niñez contra violencia género', lt:'216-227', esc:'Comunidad', f:'Abril', pda:'Indaga luchas sociales, analiza violencia.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Ubuntu', lt:'278-291', esc:'Escolar', f:'Abril', pda:'Argumenta pertinencia prácticas comunitarias.'},
    {g:5, c:'Lenguaje', p:'Sobre cuentos y poemas', lt:'64-75', esc:'Escolar', f:'Mayo', pda:'Lee y selecciona cuentos y poemas.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Principios éticos derechos', lt:'198-', esc:'Aula', f:'Mayo', pda:'Analiza ejemplos normas y leyes.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Estilos de vida y riesgos', lt:'180-197', esc:'Comunidad', f:'Mayo', pda:'Analiza estilos de vida, impacto biodiversidad.'},
    {g:5, c:'Lenguaje', p:'¿Cómo entendemos el arte?', lt:'38-49', esc:'Escolar', f:'Mayo', pda:'Explora manifestaciones culturales.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Juntos hacemos comunidad', lt:'280-293', esc:'Comunidad', f:'Mayo', pda:'Analiza fenómenos sociales.'},
    {g:5, c:'Lenguaje', p:'Detectives sociales', lt:'68-79', esc:'Comunidad', f:'Mayo', pda:'Realiza encuestas, redacta carta.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Niños hacemos democracia', lt:'210-221', esc:'Escolar', f:'Junio', pda:'Investiga transformaciones formas gobierno.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Foro de salud e higiene', lt:'320-331', esc:'Comunidad', f:'Junio', pda:'Construye alternativas saludables.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Feria de los sentimientos', lt:'320-339', esc:'Escolar', f:'Junio', pda:'Intercambia experiencias placer/displacer.'},
    {g:5, c:'Saberes y Pensamiento Científico', p:'Objetos bailarines', lt:'162-175', esc:'Aula', f:'Junio', pda:'Experimenta con imanes.'},
    {g:5, c:'Ética, Naturaleza y Sociedades', p:'Maíz, sabor a México', lt:'254-265', esc:'Comunidad', f:'Junio', pda:'Reflexiona importancia maíz.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Lo que soy, lo que quiero ser', lt:'278-289', esc:'Aula', f:'Julio', pda:'Analiza intereses, identifica metas.'},
    {g:5, c:'De lo Humano y lo Comunitario', p:'Un lugar que me representa', lt:'268-279', esc:'Comunidad', f:'Julio', pda:'Construye alternativas saludables.'},

    // ================= 6º GRADO =================
    {g:6, c:'Lenguaje', p:'El reglamento ilustrado', lt:'50-59', esc:'Aula', f:'Septiembre', pda:'Reconoce la función de los reglamentos; escribe reglas para la convivencia.'},
    {g:6, c:'Ética, Naturaleza y Sociedades', p:'Conflictos que rompen la paz', lt:'208-227', esc:'Comunidad', f:'Septiembre', pda:'Analiza críticamente conflictos territoriales; realiza propuestas de paz.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Mi familia es mi gran equipo', lt:'264-277', esc:'Aula', f:'Septiembre', pda:'Diseña e interactúa en escenarios de convivencia familiar para fortalecer autonomía.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Trabajo conjunto bien vivir', lt:'228-243', esc:'Escolar', f:'Septiembre', pda:'Valora el respeto y colaboración en el cuidado sustentable de la biodiversidad.'},
    {g:6, c:'Ética, Naturaleza y Sociedades', p:'Si nos organizamos la cuidamos', lt:'192-207', esc:'Comunidad', f:'Septiembre', pda:'Indaga sobre la importancia del agua; reflexiona sobre el derecho humano al agua potable.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'¿Quiénes somos?', lt:'272-281', esc:'Escolar', f:'Septiembre', pda:'Valora logros y retos en la historia personal para definir aspiraciones.'},
    {g:6, c:'Lenguaje', p:'El tiempo de los sueños', lt:'60-69', esc:'Escolar', f:'Septiembre', pda:'Lee textos autobiográficos; organiza sucesos en narración coherente.'},
    {g:6, c:'Lenguaje', p:'Disfrutemos textos del lugar', lt:'86-95', esc:'Comunidad', f:'Octubre', pda:'Producción de fragmentos literarios ilustrados sobre el entorno local.'},
    {g:6, c:'Lenguaje', p:'Mi comunidad se expresa', lt:'96-107', esc:'Comunidad', f:'Octubre', pda:'Selecciona y lee cuentos y poemas; elabora una antología.'},
    {g:6, c:'Lenguaje', p:'Textos que no son cuento', lt:'36-49', esc:'Aula', f:'Octubre', pda:'Localiza y lee textos expositivos; reconoce causa-consecuencia.'},
    {g:6, c:'Lenguaje', p:'Campaña social basura', lt:'30-37', esc:'Escolar', f:'Octubre', pda:'Analiza anuncios publicitarios; elabora afiche.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Comité Prevención Desastres', lt:'178-193', esc:'Escolar', f:'Octubre', pda:'Investiga desastres; analiza riesgos y zonas seguras.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Lo que elijo para bienestar', lt:'330-339', esc:'Aula', f:'Octubre', pda:'Promueve hábitos higiene y alimentación; analiza riesgos.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Ingenieros a la obra', lt:'110-129', esc:'Comunidad', f:'Octubre', pda:'Analiza problemas ambientales; propone diseño sustentable.'},
    {g:6, c:'Ética, Naturaleza y Sociedades', p:'Violencia de género', lt:'228-241', esc:'Comunidad', f:'Noviembre', pda:'Analiza críticamente causas y consecuencias de la violencia de género.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Lucha armada justicia social', lt:'244-255', esc:'Escolar', f:'Noviembre', pda:'Indaga fuentes sobre el Porfiriato y la Revolución.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'El poder de la alimentación', lt:'140-151', esc:'Aula', f:'Noviembre', pda:'Analiza etiquetas de alimentos; propone platillos saludables.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Publicidad en marcha', lt:'288-299', esc:'Aula', f:'Noviembre', pda:'Diseña carteles inclusivos que respeten la diversidad corporal.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Hábitos con-sentidos', lt:'306-317', esc:'Comunidad', f:'Noviembre', pda:'Promueve hábitos alimenticios saludables; crea recetario.'},
    {g:6, c:'Lenguaje', p:'Cultivamos soluciones', lt:'38-49', esc:'Escolar', f:'Noviembre', pda:'Identifica necesidades; elabora tríptico informativo.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Guardianes de la naturaleza', lt:'160-179', esc:'Comunidad', f:'Noviembre', pda:'Analiza problemas ambientales; diseña guía de soluciones.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Juguemos entre Todxs', lt:'318-327', esc:'Comunidad', f:'Diciembre', pda:'Valora experiencias de convivencia; fomenta empatía.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Celebremos la navidad', lt:'360-371', esc:'Escolar', f:'Diciembre', pda:'Investiga tradiciones navideñas; organiza festival.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'El peso de nuestro cuerpo', lt:'152-161', esc:'Aula', f:'Diciembre', pda:'Describe fuerza gravitacional; elabora pesas.'},
    {g:6, c:'Ética, Naturaleza y Sociedades', p:'La migración, cambio fronteras', lt:'246-261', esc:'Aula', f:'Enero', pda:'Reconoce flujos migratorios; elabora propuestas solidarias.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Lo que yo elijo', lt:'330-339', esc:'Aula', f:'Enero', pda:'Promueve hábitos de higiene y alimentación.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Si se oxida o se quema', lt:'118-129', esc:'Escolar', f:'Enero', pda:'Explica procesos de combustión y oxidación.'},
    {g:6, c:'Lenguaje', p:'Soy pasado y presente', lt:'92-101', esc:'Escolar', f:'Enero', pda:'Explora elementos simbólicos; fortalece identidad.'},
    {g:6, c:'Lenguaje', p:'Textos discontinuos', lt:'10-19', esc:'Comunidad', f:'Enero', pda:'Reconoce y produce textos discontinuos.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Publicidad diversidad', lt:'288-299', esc:'Aula', f:'Enero', pda:'Diseña carteles inclusivos.'},
    {g:6, c:'Lenguaje', p:'Comunidades correspondencia', lt:'36-49', esc:'Comunidad', f:'Febrero', pda:'Lee y analiza cartas personales.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'El poder de la alimentación', lt:'140-151', esc:'Aula', f:'Febrero', pda:'Analiza etiquetas; crea calculadora IMC.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Iluminado Escuela', lt:'130-141', esc:'Escolar', f:'Febrero', pda:'Comprende electricidad; elabora botella luminosa.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'La superclase', lt:'292-301', esc:'Escolar', f:'Febrero', pda:'Organiza clase abierta; promueve actividad física.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Piénsalo la próxima vez', lt:'302-315', esc:'Escolar', f:'Febrero', pda:'Reflexiona sobre conflictos; organiza campaña paz.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Reporteros en acción', lt:'258-271', esc:'Escolar', f:'Febrero', pda:'Identifica conflictos; propone soluciones.'},
    {g:6, c:'Lenguaje', p:'¿Por qué ellos sí?', lt:'86-95', esc:'Aula', f:'Marzo', pda:'Lee y organiza textos informativos.'},
    {g:6, c:'Lenguaje', p:'Juntos comprendemos', lt:'72-85', esc:'Aula', f:'Marzo', pda:'Reflexiona sobre cartas formales.'},
    {g:6, c:'Lenguaje', p:'Debates breves', lt:'60-71', esc:'Aula', f:'Marzo', pda:'Prepara argumentos; participa en debates.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Mi familia, mi escuela', lt:'282-291', esc:'Escolar', f:'Marzo', pda:'Organiza actividades; diseña historietas.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'El poder de la alimentación', lt:'140-151', esc:'Aula', f:'Marzo', pda:'Analiza etiquetas; crea calculadora IMC.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Del Sistema Solar', lt:'104-117', esc:'Escolar', f:'Marzo', pda:'Reconoce propiedades gases; analiza funciones vitales.'},
    {g:6, c:'Lenguaje', p:'Textos discontinuos', lt:'10-19', esc:'Comunidad', f:'Marzo', pda:'Reconoce y produce textos discontinuos.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Construyamos bien común', lt:'328-339', esc:'Comunidad', f:'Abril', pda:'Reflexiona discriminación; organiza foro.'},
    {g:6, c:'Ética, Naturaleza y Sociedades', p:'Manifiesto derechos niñez', lt:'216-229', esc:'Aula', f:'Abril', pda:'Reconoce maltrato; redacta manifiesto.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Si se oxida o quema', lt:'118-129', esc:'Escolar', f:'Abril', pda:'Explica combustión; redacta cuento.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Tu salud es una obra', lt:'344-353', esc:'Escolar', f:'Abril', pda:'Investiga higiene; elabora memorama.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Mosaico de biodiversidad', lt:'130-143', esc:'Comunidad', f:'Abril', pda:'Observa simetría; construye papalote.'},
    {g:6, c:'Lenguaje', p:'Cuidándonos del impostor', lt:'50-61', esc:'Comunidad', f:'Mayo', pda:'Consulta noticias; elabora infografía.'},
    {g:6, c:'Lenguaje', p:'Colectivizarte', lt:'82-91', esc:'Escolar', f:'Mayo', pda:'Representa acontecimientos; organiza happening.'},
    {g:6, c:'Lenguaje', p:'Juguemos a la mesa', lt:'20-29', esc:'Escolar', f:'Mayo', pda:'Lee textos polémicos; redacta argumentos.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Paso a paso hacia futuro', lt:'340-353', esc:'Aula', f:'Mayo', pda:'Indaga oferta educativa; proyecta horizontes.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Iluminando mi escuela', lt:'130-141', esc:'Escolar', f:'Mayo', pda:'Experimenta circuitos; elabora botella luminosa.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Nuestros vecinos estelares', lt:'142-159', esc:'Escolar', f:'Mayo', pda:'Describe universo; construye astrolabio.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Mi familia es mi gran equipo', lt:'264-277', esc:'Aula', f:'Junio', pda:'Diseña e interactúa en escenarios convivencia.'},
    {g:6, c:'Saberes y Pensamiento Científico', p:'Mosaico biodiversidad', lt:'130-143', esc:'Comunidad', f:'Junio', pda:'Observa simetría; construye papalote.'},
    {g:6, c:'Lenguaje', p:'El ojo crítico', lt:'24-35', esc:'Aula', f:'Junio', pda:'Lee textos explicativos; redacta descriptivos.'},
    {g:6, c:'Lenguaje', p:'Tormenta de miradas', lt:'70-81', esc:'Escolar', f:'Junio', pda:'Analiza temáticas sociales; crea mural.'},
    {g:6, c:'Lenguaje', p:'¡Reseñemos nuestra escuela!', lt:'20-35', esc:'Comunidad', f:'Junio', pda:'Reconoce reseñas; organiza galería.'},
    {g:6, c:'De lo Humano y lo Comunitario', p:'Con los pies ligeros', lt:'278-287', esc:'Aula', f:'Julio', pda:'Aplica habilidades motrices; organiza coreografía.'},
    {g:6, c:'Lenguaje', p:'Soy pasado y presente', lt:'92-101', esc:'Escolar', f:'Julio', pda:'Explora elementos simbólicos; danza ritual.'}
];

db.serialize(() => {
    console.log("🧹 Limpiando tablas antiguas...");
    db.run("DROP TABLE IF EXISTS pdas");
    db.run("DROP TABLE IF EXISTS proyectos");
    
    // CREAR TABLAS MAESTRAS
    db.run(`CREATE TABLE IF NOT EXISTS pdas (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        grado INTEGER,
        campo TEXT,
        descripcion TEXT,
        contenido TEXT,
        estado TEXT DEFAULT 'Pendiente',
        proyecto_sugerido TEXT,
        paginas_libro TEXT,
        escenario TEXT
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS proyectos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nombre TEXT,
        metodologia TEXT,
        escenario TEXT,
        temporalidad TEXT,
        problemática TEXT,
        grado INTEGER,
        pdas_seleccionados TEXT,
        fases_contenido TEXT,
        evaluacion TEXT
    )`);

    // Tablas auxiliares
    db.run("CREATE TABLE IF NOT EXISTS alumnos (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, activo INTEGER DEFAULT 1)");
    db.run("CREATE TABLE IF NOT EXISTS criterios (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, porcentaje REAL)");
    db.run("CREATE TABLE IF NOT EXISTS evaluaciones_diarias (id INTEGER PRIMARY KEY AUTOINCREMENT, alumno_id INTEGER, criterio_id INTEGER, fecha TEXT, valor REAL)");
    db.run("CREATE TABLE IF NOT EXISTS planeaciones (grado INTEGER, semana INTEGER, lunes_inicio TEXT, lunes_desarrollo TEXT, lunes_cierre TEXT, martes_inicio TEXT, martes_desarrollo TEXT, martes_cierre TEXT, miercoles_inicio TEXT, miercoles_desarrollo TEXT, miercoles_cierre TEXT, jueves_inicio TEXT, jueves_desarrollo TEXT, jueves_cierre TEXT, viernes_inicio TEXT, viernes_desarrollo TEXT, viernes_cierre TEXT, recursos TEXT, evaluacion TEXT, adecuaciones TEXT, PRIMARY KEY (grado, semana))");
    db.run("CREATE TABLE IF NOT EXISTS perfiles_alumnos (alumno_id INTEGER PRIMARY KEY, nombre_mama TEXT, tel_mama TEXT, nombre_papa TEXT, tel_papa TEXT, tipo_sangre TEXT, alergias TEXT, servicio_medico TEXT, adaptaciones TEXT, direccion TEXT, emergencia_nombre TEXT, emergencia_parentezco TEXT, emergencia_telefono TEXT, emergencia_direccion TEXT)");
    db.run("CREATE TABLE IF NOT EXISTS incidencias (id INTEGER PRIMARY KEY AUTOINCREMENT, alumno_id INTEGER, fecha TEXT, situacion TEXT, involucrados TEXT, medidas TEXT)");
    db.run("CREATE TABLE IF NOT EXISTS comisiones (id INTEGER PRIMARY KEY AUTOINCREMENT, descripcion TEXT, fecha TEXT, tipo TEXT)");
    db.run("CREATE TABLE IF NOT EXISTS eventos_calendario (fecha TEXT PRIMARY KEY, tipo TEXT)");

    // INYECCIÓN
    console.log("🌱 Sembrando datos masivos...");
    const stmt = db.prepare("INSERT INTO pdas (grado, campo, proyecto_sugerido, paginas_libro, escenario, descripcion) VALUES (?,?,?,?,?,?)");
    const stmtProy = db.prepare("INSERT INTO proyectos (nombre, metodologia, escenario, temporalidad, grado, pdas_seleccionados, fases_contenido) VALUES (?,?,?,?,?,?,?)");

    db.run("BEGIN TRANSACTION");
    DATA_REAL.forEach(i => {
        // 1. Insertar PDA
        stmt.run(i.g, i.c, i.p, i.lt, i.esc, i.pda);
        
        // 2. Insertar Proyecto
        let metodo = METODOS[Object.keys(METODOS).find(k => i.c.includes(k))] || 'COMUNITARIOS';
        stmtProy.run(i.p, metodo, i.esc, i.f, i.g, '[]', '{}');
    });
    db.run("COMMIT");
    stmt.finalize();
    stmtProy.finalize();

    console.log(`✅ ¡ÉXITO! Base de datos recargada con ${DATA_REAL.length} registros (1º a 6º Grado).`);
});

setTimeout(() => { 
    db.close((err) => {
        if (err) console.error(err.message);
        else console.log('Conexión a la base de datos cerrada.');
    }); 
}, 3000);