name: Build Mac and Windows App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build macOS App
      run: npm run dist -- --mac --universal
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Upload Mac Installer
      uses: actions/upload-artifact@v4
      with:
        name: Planificador-Docente-Mac
        path: release/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Windows App
      run: npm run dist -- --win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: Planificador-Docente-Windows
        path: release/*.exe
